'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property RegistrationNumber As String
    Public Property FullName As String
    Public Property Gender As String
    Public Property Age As Nullable(Of Decimal)
    Public Property Address As String
    Public Property PhoneNumber As String
    Public Property Email As String
    Public Property [Class] As String
    Public Property Picture As Byte()
    Public Property Image As Byte()
    Public Property [Date] As Nullable(Of Date)

End Class
